### ISSUE TITLE
Sampling Bijector Distribution Not Working on TFP 0.12.0:  AttributeError: 'NoneType' object has no attribute 'items'

### ISSUE THREAD

**Issue by WillianFuks** [tensorflow/probability#1202]
I'm using this bijector:

```
invg = tfd.InverseGamma(1, 1)

class SquareRootBijector(tfb.Bijector):
    """
    Compute `Y = g(X) = X ** (1 / 2) which transforms variance into standard deviation.
    Main reference for building this bijector is the original [PowerTransform](https://github.com/tensorflow/probability/blob/v0.11.1/tensorflow_probability/python/bijectors/power_transform.py) # noqa: E501
    """
    def __init__(
        self,
        validate_args: bool = False,
        name: str = 'square_root_bijector'
    ):
        """
        Args
        ----
          validate_args: bool
              Indicates whether arguments should be checked for correctness.
          name: str
              Name given to ops managed by this object.
        """
        with tf.name_scope(name) as name:
            super().__init__(forward_min_event_ndims=0, validate_args=validate_args,
                             name=name)

    def _forward(self, x: Union[float, np.array, tf.Tensor]) -> tf.Tensor:
        """
        Implements the forward pass `G` as given by `Y = G(X)`. In this case, it's a
        simple square root of X.
        Args
        ----
          x: Union[float, np.array, tf.Tensor])
              Variable `X` to receive the transformation.
        Returns
        -------
          X: tf.Tensor
              Square root of `x`.
        """
        return tf.sqrt(x)

    def _inverse(self, y: Union[float, np.array, tf.Tensor]) -> tf.Tensor:
        """
        Implements G^-1(y).
        Args
        ----
          y: Union[float, np.array, tf.Tensor]
              Values to be transformed back. In this case, they will be squared.
        Returns
        -------
          y: tf.Tensor
              Squared `y`.
        """
        return tf.square(y)

    def _inverse_log_det_jacobian(self, y: tf.Tensor) -> tf.Tensor:
        """
        When transforming from `P(X)` to `P(Y)` it's necessary to compute the log of the
        determinant of the Jacobian matrix for each correspondent function `G` which
        accounts for the volumetric transformations on each domain.
        The inverse log determinant is given by:
        `ln(|J(G^-1(Y)|) = ln(|J(Y ** 2)|) = ln(|2 * Y|) = ln(2 * Y)`
        Args
        ----
          y: tf.Tensor
        Returns
        -------
          tf.Tensor
        """
        return tf.math.log(2 * y)

    def _forward_log_det_jacobian(self, x: tf.Tensor) -> tf.Tensor:
        """
        Computes the volumetric change when moving forward from `P(X)` to `P(Y)`, given
        by:
        `ln(|J(G(X))|) = ln(|J(sqrt(X))|) = ln(|(1 / 2) * X ** (-1 / 2)|) =
                       = (-1 / 2) * ln(4.0 * X)
        Args
        ----
          x: tf.Tensor
        Returns
        -------
          tf.tensor
        """
        return -0.5 * tf.math.log(4.0 * x)

bijector = SquareRootBijector()
new_dist = tfd.TransformedDistribution(invg, bijector)
```

When running sampling on TFP 0.12.0 I get the following:

    new_dist.sample()

> ---------------------------------------------------------------------------
> 
> AttributeError                            Traceback (most recent call last)
> 
> <ipython-input-30-3ac543978629> in <module>()
> ----> 1 new_dist.sample()
> 
> 13 frames
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/bijectors/bijector.py in parameters(self)
>     649     # if the subclass used:
>     650     # `parameters = dict(locals())`.
> --> 651     return {k: v for k, v in self._parameters.items()
>     652             if not k.startswith('__') and k != 'self'}
>     653 
> 
> AttributeError: 'NoneType' object has no attribute 'items'
> 
> 

This is breaking other operations that uses as input this transformed one. On version 0.11.1 it works fine. Is there something that needs updating on how to implement the bijector?

Thanks,

**Comment by davmre** [comment]
The Bijector base class expects a `parameters` dictionary containing all constructor arguments to the bijector:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/bijectors/tanh.py#L48
(this is used, among other purposes, to share the input/output cache between multiple instances of a bijector with the same parameters---I think this was added since the last release and is causing the error you're seeing). See here for an example of setting it:
https://github.com/tensorflow/probability/blob/master/tensorflow_probability/python/bijectors/tanh.py#L48

As an aside, I think the built-in `tfb.Invert(tfb.Square())` or `tfb.Power(0.5)` would suffice for your use case. :-)

**Comment by WillianFuks** [comment]
Thanks @davmre for the help and quick answer :)!

I've already fixed the issue.

Best Regards,

Will
