### ISSUE TITLE
joint_distribution._DefaultJointBijector is broken in nightly

### ISSUE THREAD

**Issue by amol447** [tensorflow/probability#1026]
Hi,
The following code will work with tfp 0.10.0 but breaks in the nightly because of the DefaultJointBijector having multiple bugs. What won't show up in this example but is also suspect is it seems to move along batch dimension rather than event dimension in the _evaluate_bijector function in joint_distribution.py
```
import numpy as np
import tensorflow_probability as tfp
import tensorflow as tf
tfd=tfp.distributions
weights=np.random.multivariate_normal(np.arange(1,3),np.diag([4.0,6.0]),3)
design_matrix=np.random.normal(4,2,(3,200,2))
tseries = np.einsum('ij,ikj->ik',weights,design_matrix)
Root = tfd.JointDistributionCoroutine.Root
def joint_model():
    yield Root(tfd.Exponential(1.0))
    yield Root(tfd.Exponential(1.0))

model=tfp.sts.Sum([tfp.sts.LinearRegression(design_matrix=design_matrix.astype(np.float32),weights_prior=tfd.Blockwise(tfd.JointDistributionCoroutine(joint_model)))],observed_time_series=tseries.astype(np.float32))
variational_posterior = tfp.sts.build_factored_surrogate_posterior(model)
optimizer = tf.optimizers.Adam(learning_rate=0.1)
loss_curve=tfp.vi.fit_surrogate_posterior(target_log_prob_fn=model.joint_log_prob(observed_time_series=tseries.astype(np.float32)),
                                                     surrogate_posterior=variational_posterior,optimizer=optimizer,num_steps=500)
AttributeError: 'tuple' object has no attribute 'dtype'
```
