### ISSUE TITLE
Error on import of tensorflow_probability

### ISSUE THREAD

**Issue by aleccrowell** [tensorflow/probability#321]
With:

> tensorflow = 1.13.1
>tensorflow_probability = 0.6.0

```
import tensorflow_probability as tfp
```

produces:

```
Traceback (most recent call last):

  File "<ipython-input-3-41494c8c96ff>", line 1, in <module>
    import tensorflow_probability as tfp

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_probability\__init__.py", line 78, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_probability\python\__init__.py", line 21, in <module>
    from tensorflow_probability.python import bijectors

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_probability\python\bijectors\__init__.py", line 46, in <module>
    from tensorflow_probability.python.bijectors.matveclu import MatvecLU

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_probability\python\bijectors\matveclu.py", line 24, in <module>
    from tensorflow_probability.python.math.linalg import lu_reconstruct

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_probability\python\math\__init__.py", line 22, in <module>
    from tensorflow_probability.python.math.diag_jacobian import diag_jacobian

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow_probability\python\math\diag_jacobian.py", line 24, in <module>
    tfe = tf.contrib.eager

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 61, in __getattr__
    module = self._load()

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 44, in _load
    module = importlib.import_module(self.__name__)

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\__init__.py", line 40, in <module>
    from tensorflow.contrib import distribute

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\distribute\__init__.py", line 33, in <module>
    from tensorflow.contrib.distribute.python.tpu_strategy import TPUStrategy

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\distribute\python\tpu_strategy.py", line 28, in <module>
    from tensorflow.contrib.tpu.python.tpu import tpu

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\tpu\python\tpu\tpu.py", line 24, in <module>
    from tensorflow.contrib.compiler import xla

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\contrib\compiler\xla.py", line 28, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib

  File "C:\Users\L352104\AppData\Local\Continuum\anaconda3\lib\site-packages\tensorflow\python\estimator\model_fn.py", line 26, in <module>
    from tensorflow_estimator.python.estimator import model_fn

ImportError: cannot import name 'model_fn'
```

**Comment by csuter** [comment]
What's in your `pip list`? TF estimators moved on it's own package in 1.13. Looks like there might be some conflicting versions of things installed.

**Comment by jvdillon** [comment]
Try this:
`pip install --upgrade tf-nightly-gpu-2.0-preview tfp-nightly`

**Comment by aleccrowell** [comment]
going to nightly for both resulted in a new error:

`AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v2'`

with a little googling I was able to determine this is a compatibility issue related to the 2.0 alpha.
 After doing a clean pip uninstall/pip install with `tensorflow==2.0.0-alpha0 ` and `tfp-nightly` I'm successfully able to import tfp!

**Comment by jvdillon** [comment]
Hi @aleccrowell. Im surprised `tensorflow==2.0.0-alpha0` worked as a dependency. Did you mean to say `tf-nightly-gpu-2.0-preview`? (The latter is what `tfp-nightly` is tested against.)

**Comment by Dpananos** [comment]
So to be clear, should tensorflow_probability work with the 2.0 alpha?  I'm interested in recreating examples shown [here](https://medium.com/tensorflow/regression-with-probabilistic-layers-in-tensorflow-probability-e46ff5d37baf?linkId=64696542)

**Comment by axch** [comment]
We expect our nightly release `tfp-nightly` to work with TF's 1.x nightly and also TF 2.0 alpha.  At the moment we are not able to make a stable release that will work with both TF 1.13.x and TF 2.0 alpha.

**Comment by jvdillon** [comment]
Try this:
`pip install --upgrade tf-nightly-gpu-2.0-preview tfp-nightly`
(Drop the -gpu if you don't have one or want a smaller whl download.)

tfp-nightly is tested against `tf-nightly-gpu-2.0-preview` *not*
 `tensorflow==2.0.0-alpha0`.

**Comment by noirmist** [comment]
> `pip install --upgrade tf-nightly-gpu-2.0-preview tfp-nightly`

I tried this code and I can't import tensorflow_probability
```!pip install --upgrade tf-nightly-gpu-2.0-preview tfp-nightly
import tensorflow as tf
tf.__version__
import tensorflow_probability as tfp
tfp.__version__
```

```
ImportError                               Traceback (most recent call last)
<ipython-input-1-e115b75610f9> in <module>()
      3 import tensorflow as tf
      4 tf.__version__
----> 5 import tensorflow_probability as tfp
      6 tfp.__version__

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/__init__.py in <module>()
     76 
     77 # from tensorflow_probability.google import staging  # DisableOnExport
---> 78 from tensorflow_probability.python import *  # pylint: disable=wildcard-import
     79 from tensorflow_probability.python.version import __version__
     80 # pylint: enable=g-import-not-at-top

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/__init__.py in <module>()
     23 from tensorflow_probability.python import edward2
     24 from tensorflow_probability.python import glm
---> 25 from tensorflow_probability.python import layers
     26 from tensorflow_probability.python import math
     27 from tensorflow_probability.python import mcmc

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/__init__.py in <module>()
     29 from tensorflow_probability.python.layers.dense_variational import DenseReparameterization
     30 from tensorflow_probability.python.layers.dense_variational_v2 import DenseVariational
---> 31 from tensorflow_probability.python.layers.distribution_layer import CategoricalMixtureOfOneHotCategorical
     32 from tensorflow_probability.python.layers.distribution_layer import DistributionLambda
     33 from tensorflow_probability.python.layers.distribution_layer import IndependentBernoulli

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/distribution_layer.py in <module>()
     37 from tensorflow_probability.python.internal import distribution_util as dist_util
     38 from tensorflow_probability.python.layers.internal import distribution_tensor_coercible as dtc
---> 39 from tensorflow_probability.python.layers.internal import tensor_tuple as tensor_tuple
     40 from tensorflow.python.keras.utils import tf_utils as keras_tf_utils  # pylint: disable=g-direct-tensorflow-import
     41 

/usr/local/lib/python3.6/dist-packages/tensorflow_probability/python/layers/internal/tensor_tuple.py in <module>()
     21 import tensorflow as tf
     22 
---> 23 from tensorflow.python.framework import composite_tensor  # pylint: disable=g-direct-tensorflow-import
     24 
     25 

ImportError: cannot import name 'composite_tensor'
```

**Comment by csuter** [comment]
This is somewhat surprising. Are you still seeing it? (I'm wondering if it was a transient issue in tf-nightly)

**Comment by noirmist** [comment]
> This is somewhat surprising. Are you still seeing it? (I'm wondering if it was a transient issue in tf-nightly)

No. not right now.
```
tf version: 2.0.0-dev20190409
tfp version: 0.7.0-dev
```
This version is currently working

**Comment by JessicaWoods03** [comment]
Question? tensorflow_probability is blowing up on my googlelabs while using tensorflow_version 2.x.....I tried the upgrade for HiddenMarkovModel...and it blew up LOL
!pip install tensorflow_probability==0.8.0rc0 --user --upgrade

It's saying my import is failing due to a missing package after I upgraded it-
Any suggestions to trouble shoot this?

**Comment by csuter** [comment]
Hi @JessicaWoods03 -- can you copy/paste the error message here?

Why `0.8.0rc0`? That's an old (we're on 0.12 now), not-quite-stable ("rc" == release candidate) version.

**Comment by csuter** [comment]
To clarify -- i'd suggest using `tensorflow_probability==0.12.1` along with `tensorflow==2.4.0`.

**Comment by JessicaWoods03** [comment]
I just realized that LOL- thanks I just did that and it updated-
I am doing a tutorial on FreeCodeCamp...for the neural networks part- I know machine learning for python but not deep learning too well- So I am putting my toes in the water so to speak- LOL

**Comment by csuter** [comment]
No worries, glad you're unblocked. Let us know if you run into more issues.
