### ISSUE TITLE
Plans to support model.predict() for Keras Sequential models with DistributionLambda?

### ISSUE THREAD

**Issue by skeydan** [tensorflow/probability#427]
Hi,

from our side (R wrapper to TFP) it would be helpful to know if it is planned to support `model.predict()` for models using `DistributionLambda`

e.g.

```
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions

w0 = 0.125
b0 = 5.
x_range = [-20, 60]

def load_dataset(n=150, n_tst=150):
  np.random.seed(43)
  def s(x):
    g = (x - x_range[0]) / (x_range[1] - x_range[0])
    return 3 * (0.25 + g**2.)
  x = (x_range[1] - x_range[0]) * np.random.rand(n) + x_range[0]
  eps = np.random.randn(n) * s(x)
  y = (w0 * x * (1. + np.sin(x)) + b0) + eps
  x = x[..., np.newaxis]
  x_tst = np.linspace(*x_range, num=n_tst).astype(np.float32)
  x_tst = x_tst[..., np.newaxis]
  return y, x, x_tst

y, x, x_tst = load_dataset()

model = tf.keras.Sequential([
  tf.keras.layers.Dense(1 + 1),
  tfp.layers.DistributionLambda(
      lambda t: tfd.Normal(loc=t[..., :1],
                           scale=1e-3 + tf.math.softplus(0.05 * t[...,1:]))),
])

negloglik = lambda y, rv_y: -rv_y.log_prob(y)
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01), loss=negloglik)
model.fit(x, y, epochs=1, verbose=False);

# this is currently used and works
#yhat = model(x_tst)
# this currently does not work
model.predict(x_tst)

```

Currently this results in

```
AttributeError: 'Normal' object has no attribute 'type'
```

Thank you!

**Comment by Quetzalcohuatl** [comment]
I think that after `yhat = model(x_tst)`, then `yhat` contains the predictions. You can see in `yhat.__dict__` and you can see there are predictions in there. In the tutorial they did `predictions = [model(x_tst) for i in range(100)]` to get multiple predictions

**Comment by skeydan** [comment]
Yeah, this question was about the available syntax - in order to know  if from the R side, `predict` should work for these models... By now I assume that probably, __call__ must be the only feasible syntax here (which is not a problem).

**Comment by nbro** [comment]
@skeydan  Why was this issue closed? This is a real issue because it doesn't allow us to call the common method `predict` to perform predictions. You should support the call to `predict` to get the predictions, even when using distributions as outputs of the network.

**Comment by Quetzalcohuatl** [comment]
@nbro You have to use `model(x)` instead of `model.predict(x)`

**Comment by nbro** [comment]
@Quetzalcohuatl I understand I can only use `model(x)`, but `predict` should work with TFP too. There should be a default behaviour.

**Comment by nbro** [comment]
@skeydan Your original example seems now to work with TF 2.0 or 2.1 combined with either TFP 0.8 or TFP 0.9. 

Which version of TF and TFP were you using at the time you got the error?

**Comment by skeydan** [comment]
Thanks @nbro, that's good to know!

**Comment by nbro** [comment]
@skeydan Meanwhile, I've found a situation where this error is still raised. See https://github.com/tensorflow/tensorflow/issues/34765#issuecomment-580359337.

**Comment by skeydan** [comment]
Aha ok, so it would not yet work with tensors it looks like...

**Comment by nbro** [comment]
@skeydan It will not work at least when you have Bayesian convolutional layers in your model, because, in that case, you need `experimental_run_tf_function=False`, but this causes `predict` not to work.
